### PR TITLE
Add Ruby 2.3 and 2.4 to test matrix.

### PR DESCRIPTION
**Pull request by connorshea**
Happy holidays!

### CODE REVIEW

**Comment by connorshea** [comment]
Until rails/rails@47c4924 is released in Rails 4.2.8, Ruby 2.4 won't work with it.

**Comment by jacobbednarz** [comment]
This is great! I'm looking to start testing out app on 2.4 this week so this saves me a PR!

I'd be fine moving 2.4 to the "allowed failures" for now and next lot of changes that come in can check whether that fix has landed.

**Comment by connorshea** [comment]
@jacobbednarz Rails 4.2.8 should be coming out soon, so that's not really a problem.

**Comment by oreoshake** [comment]
Ugh, that's an annoying failure. I hate C.

**Comment by connorshea** [comment]
@oreoshake looks like the webhook delay is preventing tests from running, but whenever that ends this should pass.

**Comment by oreoshake** [comment]
Hmm, I can't force a build on travis.

**Comment by oreoshake** [comment]
It passed: https://travis-ci.org/twitter/secureheaders/builds/186904045

**Pull request merged**
