### PR TITLE
Restore Rails 2 support

### PR DESCRIPTION
**Pull request by solenko**
## All PRs:

* [x] Has tests
* [ ] Documentation updated

When include ActionController::Base.include(::SecureHeaders) called from reiltie.rb,
SecuerHeaders.add_features not defined yet.
As a result class/instance methods won't added to ActionController::Base.

But introduced in commit 4aee15ef85c7413aa6718a1ec9ea82f843eb6d03

### CODE REVIEW

**Comment by solenko** [comment]
Build failure not related to my changes -- seems build for 2.x branch broken.
Do You plan to maintain this branch?

**Comment by oreoshake** [comment]
I do plan on maintaining this branch. I can try to fix those up or you can
attempt it but I won't get to this until next week.

**Comment by solenko** [comment]
Sorry, I forgot about US holydays. Build fixed.

Happy Thanksgiving!

**Comment by oreoshake** [comment]
Released in 2.5.3

**Pull request merged**
