### PR TITLE
Add missing comma to correct hash syntax

### PR DESCRIPTION
**Pull request by mnoack**

### CODE REVIEW

**Comment by oreoshake** [comment]
Hello,

I **just** pushed the 3.x branch. However, this error also exists in the README for the newer code. Mind updating this?

**Comment by mnoack** [comment]
No problem, I also considered replacing all the ruby 1.8 style hashes with ruby 1.9 since Ruby 1.8 has been unsupported for several years.
You can basically do it yourself too if your interested with:
sed -i 's/:\([a-zA-Z0-9_]*\) =>/\1:/g' `git ls-files`

Or I can do a separate PR for that.

**Comment by mnoack** [comment]
I've re-based this branch, and tried off 3.x but couldn't, and noticed I can't see it on Github (but I do when I pull locally). I'm guessing there's some issue with the 3.x branch, but I'm sure with most people viewing the README on master (github's default) it's not critical anyway.

Let me know if you want me to PR a hash syntax update via 
```sh
sed -i 's/:([a-zA-Z0-9_]*) =>/\1:/g' git ls-files
```

**Comment by oreoshake** [comment]
Bah, I'm terribly sorry I miscommunicated. I just **merged** the 3.x branch to master. I just deleted the 3.x branch after merging it.

I'd definitely be open to switching to the 1.9 syntax. I supported ruby 1.8 for a very long time, but support was dropped in the 3.x branch.

**Pull request merged**
