### PR TITLE
small typo fix: a minimum … IS required

### PR DESCRIPTION
**Pull request by s-gerber**
This PR fixes just a small typo.

Thank you for your work

### CODE REVIEW

**Comment by jacobbednarz** [comment]
Howdy @s-gerber!

Thanks for the contribution! 🎈 I'm pretty average with the English language however it looks like "are" is the correct usage in this case - see [grammarly on is vs are usage](https://www.grammarly.com/blog/is-vs-are/). Here we are talking about multiple pins so the noun (pins) is plural.

**Comment by oreoshake** [comment]
I abstain. Tie vote goes to @gregose.

**Comment by gregose** [comment]
Oh no... grammar sniped. I did a couple minutes of intense internet grammar research and while it seems like it could go either way, I like the rule of thumb proposed at http://grammar.ccc.commnet.edu/grammar/grammarlogs3/grammarlogs488.htm.

> You'd say "A variety of cigars is a good thing" because it's the variety, a singular notion, that you're emphasizing. On the other hand, you might say "A variety of good cigars are available" when you want to emphasize a number of cigars in their marvelous plurality.

In this case, it feels like here we are emphasizing that there are multiple pins required, not the singular minimum of them. My vote goes to keeping it “are.”

**Comment by oreoshake** [comment]
@s-gerber it sounds like there's disagreement here. I'm going to let this sit open for a few more days then close it out. Either way, thanks again for the contribution!

I LOVE DOCS PRs :heart:

**Comment by s-gerber** [comment]
Oh I (obviously) didn't know that `is` could be right here as well. I was just thinking that `to be` is referencing the (required) minimum here.

So absolutely no problem for me if it won't be merged. 😉

**Comment by oreoshake** [comment]
Closing this one out. It has been nearly 90 days and the public request for comments has been closed. I appreciate the discussion!

**Pull request closed without merging**
