### PR TITLE
Alternative fix for already initialized constant

### LINKED ISSUE #257: Reloading Rakefile causes already initialized constant errors
In this [test](https://github.com/linuxfoundation/cii-best-practices-badge/blob/master/test/integration/feed_test.rb), I'm reloading the Rakefile and in order to rerun the fixtures. This causes the following spurious errors:
```bash
$ rake test
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/secure_headers-3.3.1/lib/tasks/tasks.rake:1: warning: already initialized constant INLINE_SCRIPT_REGEX
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/secure_headers-3.3.1/lib/tasks/tasks.rake:1: warning: previous definition of INLINE_SCRIPT_REGEX was here
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/secure_headers-3.3.1/lib/tasks/tasks.rake:2: warning: already initialized constant INLINE_STYLE_REGEX
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/secure_headers-3.3.1/lib/tasks/tasks.rake:2: warning: previous definition of INLINE_STYLE_REGEX was here
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/secure_headers-3.3.1/lib/tasks/tasks.rake:3: warning: already initialized constant INLINE_HASH_SCRIPT_HELPER_REGEX
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/secure_headers-3.3.1/lib/tasks/tasks.rake:3: warning: previous definition of INLINE_HASH_SCRIPT_HELPER_REGEX was here
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/secure_headers-3.3.1/lib/tasks/tasks.rake:4: warning: already initialized constant INLINE_HASH_STYLE_HELPER_REGEX
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/secure_headers-3.3.1/lib/tasks/tasks.rake:4: warning: previous definition of INLINE_HASH_STYLE_HELPER_REGEX was here
```
I'm submitting a PR for the simple fix momentarily.
Cc @david-a-wheeler

### PR DESCRIPTION
**Pull request by dankohn**
Signed-off-by: Dan Kohn <dan@dankohn.com>

This is an alternative fix to #258. It also resolves #257 and addresses the comment https://github.com/twitter/secureheaders/pull/258#issuecomment-219264431 by @jacobbednarz.

### CODE REVIEW

**Comment by dankohn** [comment]
Cc @david-a-wheeler

**Comment by jacobbednarz** [comment]
You didn't need a new pull request for this one :P I would have been happy with just another (even squashed) commit on the other branch. No issues here though :+1:

LGTM.

**Comment by dankohn** [comment]
I just thought I'd show both options for clarity. These values are never falsey, so the conditional assignment works equivalently here.

But, I'm always happy to have the opportunity to learn things, in this case from this excellent blog post: http://www.rubyinside.com/what-rubys-double-pipe-or-equals-really-does-5488.html

Thanks for your review.

**Comment by oreoshake** [comment]
Does moving the definitions inside of the `namespace` block do anything?

**Comment by dankohn** [comment]
@oreoshake I just checked and moving the constant within the namespace block https://github.com/dankohn/secureheaders/commit/4bc4012e8e5b6b8104ed56b608625d4589e9df00 still results in:
```rake
$ rake test
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/secureheaders-4bc4012e8e5b/lib/tasks/tasks.rake:4: warning: already initialized constant INLINE_SCRIPT_REGEX
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/secureheaders-4bc4012e8e5b/lib/tasks/tasks.rake:4: warning: previous definition of INLINE_SCRIPT_REGEX was here
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/secureheaders-4bc4012e8e5b/lib/tasks/tasks.rake:5: warning: already initialized constant INLINE_STYLE_REGEX
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/secureheaders-4bc4012e8e5b/lib/tasks/tasks.rake:5: warning: previous definition of INLINE_STYLE_REGEX was here
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/secureheaders-4bc4012e8e5b/lib/tasks/tasks.rake:6: warning: already initialized constant INLINE_HASH_SCRIPT_HELPER_REGEX
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/secureheaders-4bc4012e8e5b/lib/tasks/tasks.rake:6: warning: previous definition of INLINE_HASH_SCRIPT_HELPER_REGEX was here
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/secureheaders-4bc4012e8e5b/lib/tasks/tasks.rake:7: warning: already initialized constant INLINE_HASH_STYLE_HELPER_REGEX
/Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/secureheaders-4bc4012e8e5b/lib/tasks/tasks.rake:7: warning: previous definition of INLINE_HASH_STYLE_HELPER_REGEX was here
Run options: --seed 42631

# Running:
```
So, please consider accepting this PR.

**Comment by oreoshake** [comment]
Released in https://github.com/twitter/secureheaders/releases/tag/v3.3.2

**Comment by dankohn** [comment]
Thanks!

**Pull request merged**
