### PR TITLE
wws: -> wss:

### PR DESCRIPTION
**Pull request by xtian**
I believe this is a typo.

### CODE REVIEW

**Comment by jacobbednarz** [comment]
You are correct 👍🏼. This typo is used in a spec too! I wonder if it plays enough of a role that this typo should have caused a failure instead of being allowed. 

On mobile at the moment but will check the whole spec out later on.

**Comment by jacobbednarz** [comment]
Looking further into it, the typo is not significant enough to cause a failure (at least the gem specs) since it is user input and there is no reason to try and validate it.

**Comment by xtian** [comment]
Yep, I just thought it could potentially be confusing for people copy-pasting the README config.

**Comment by jacobbednarz** [comment]
Agree ❤️

**Comment by oreoshake** [comment]
>  This typo is used in a spec too

Yeah, it was copy/pasted from the readme at some point. @xtian mind updating it [here](https://github.com/twitter/secureheaders/blob/76fb8284e78e1233a7cdeaee205afd8690a74f4f/spec/lib/secure_headers/headers/policy_management_spec.rb#L26) too?

And yeah, I don't see much value in validating the content. It's moderately complex and error-prone which could lead to false positives. Also, if it's invalid, things will break anyways :smile:

**Comment by xtian** [comment]
Did you mean to link to a different location? This PR already changes that line.

**Comment by oreoshake** [comment]
Oops :coffee:

**Pull request merged**
