### PR TITLE
Make gem work with Ruby 2.2.3

### PR DESCRIPTION
**Pull request by nchelluri**

### CODE REVIEW

**Comment by nchelluri** [comment]
Comment from https://github.com/twitter/secureheaders/pull/173#issue-109281205 applies here as well since the only difference is a commit message.

**Comment by oreoshake** [comment]
:metal: please enable 2.2 in .travis.yml so we can see it passing.

THANK YOU!!!

**Comment by nchelluri** [comment]
You are welcome :)

Build is faliing for 2.2, unfortunately:

```
$ bundle exec rake

..........................................................................................................................................................................................

Finished in 0.53425 seconds (files took 0.26922 seconds to load)
186 examples, 0 failures

/home/travis/build/twitter/secureheaders/fixtures/rails_3_2_12
/home/travis/build/twitter/secureheaders/vendor/bundle/ruby/2.2.0/gems/activesupport-3.2.12/lib/active_support/values/time_zone.rb:270: warning: circular argument reference - now Rack::File headers parameter replaces cache_control after Rack 1.5.
Ruby 2.2+ is not supported on Rails 3.2.12. Check the Rails release notes for the appropriate update with support.

rake aborted!
Header tests with app not using initializer failed exit code: pid 2562 exit 1
/home/travis/build/twitter/secureheaders/Rakefile:24:in `block in <top (required)>'
/home/travis/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => default => all_spec
(See full trace by running task with --trace)

The command "bundle exec rake" exited with 1.
```

**Comment by oreoshake** [comment]
Ah, I see. Well Rails 3.2.22 supports 2.0. I'll update those tests.

**Comment by oreoshake** [comment]
I've got it working in https://github.com/twitter/secureheaders/pull/175, closing this out.

**Pull request closed without merging**
