### PR TITLE
the same URL is repeated twice in the gemspec

### PR DESCRIPTION
**Pull request by ghiculescu**
i think this is a typo?

### CODE REVIEW

**Comment by jacobbednarz** [comment]
Hi @ghiculescu!

Thanks for the PR! This does indeed look like an issue:

```
$ gem install secure_headers
Fetching: useragent-0.16.8.gem (100%)
Fetching: secure_headers-5.0.3.gem (100%)

**********
:wave: secure_headers 5.0 introduces a lot of breaking changes (in the name of security!). It's highly likely you will need to update your secure_headers cookie configuration to avoid breaking things. See the upgrade guide for details: https://github.com/twitter/secureheaders/blob/master/docs/upgrading-to-4-0.md https://github.com/twitter/secureheaders/blob/master/docs/upgrading-to-4-0.md
**********

Successfully installed useragent-0.16.8
Successfully installed secure_headers-5.0.3
2 gems installed
```

**Comment by oreoshake** [comment]
Copy paste considered harmful. Oh man, secure_headers 4.0 was such a mess 🤪

**Comment by jacobbednarz** [comment]
@ghiculescu would you be able to update the URL to point at the 5.x upgrade docs? https://github.com/twitter/secureheaders/blob/master/docs/upgrading-to-5-0.md

**Comment by ghiculescu** [comment]
@jacobbednarz done!

**Comment by jacobbednarz** [comment]
LGTM ✨

**Comment by oreoshake** [comment]
Thanks!

**Pull request merged**
